### ISSUE TITLE
Просмотр

### ISSUE THREAD

**Issue by vi34** [IFMO-MobDev-2014/extratask1#12]
"Постраничный просмотр" 
Это означает, что можно открыть изображение на весь экран и просматривать одно за другим или это означает просмотр раздела делать с помощью страниц?

**Comment by thevery** [comment]
Второе.
Но первое будет большим плюсом.

**Comment by mikita95** [comment]
Правильно ли я понимаю, что нужно отображение только одного раздела?
"Написать клиент к фото-хостингу для отображения разделА "фото дня"/"популярные"/"выбор редакции"/итд."
Что должно отображаться тогда на каждой странице, если GridView отображает все картинки на одной странице(с прокруткой вниз)?

**Comment by thevery** [comment]
Одного раздела достаточно. Постраничный просмотр - это, например, 0-19, 20-39 итд, такой вариант удобнее бесконечного вертикально списка.
