### ISSUE TITLE
Длительность экзамена

### ISSUE THREAD

**Issue by marianna-b** [IFMO-MobDev-2014/extratask1#4]
Сколько времени будет длиться экзамен? И когда он будет?

**Comment by marianna-b** [comment]
Экзамен 21 января у всех или для каждой группы по расписанию?

**Comment by izban** [comment]
У групп 2538 и 2539 в расписании на сайте стоит экзамен 23 числа, и 21 января намечается экзамен по другому предмету, по матлогике. Будет ли экзамен и 23 числа? Дайте, пожалуйста, какую-нибудь более подробную информацию.

И еще вопрос вдогонку -- когда заканчивается прием обычных домашних заданий за этот семестр?

**Comment by thevery** [comment]
Обычно экзамен проходит в один день у всех сразу, но ввиду удвоенного количества групп в этом году всё будет по расписанию - две группы 21 и две - 23.
По времени - 3 часа.
Дедлайн - 18.01.15 23:59.
