### ISSUE TITLE
Количество баллов за дз

### ISSUE THREAD

**Issue by marianna-b** [IFMO-MobDev-2014/extratask1#5]
Почему изменилось количество баллов, которое можно получить за дз?
Многие, нормально и самостоятельно выполняя домашние задания, не успевают написать задание на коллоквиуме или экзамене. Теперь им нельзя получить даже оценку С.

**Comment by thevery** [comment]
Баллы за дз и экзамен были объявлены на первой лекции - 64+35

**Comment by marianna-b** [comment]
В таблице еще неделю назад количество баллов за дз обрезалось по 75.

**Comment by thevery** [comment]
Таблица - штука сугубо техническая.

**Comment by marianna-b** [comment]
В прошлом году тоже было 75

**Comment by marianna-b** [comment]
И это кажется логичными.

**Comment by svasilinets** [comment]
Дамы и господа.
Нам кажется логичным то, что, чтобы получить оценку C, надо успевать написать что-то на коллоквиумах/экзамене.  Это наша единственная проверка, что вы что-то можете сделать сами. (Хотя и тут можно считерить) Хочется заметить, что надо набрать совсем немного - 10 баллов. А для этого, надо два раза сделать задание на минимум баллов; попыток на это аж 4 штуки (два коллоквиума, одно переписывание, экзамен).
