### ISSUE TITLE
Сдать экзамен раньше?

### ISSUE THREAD

**Issue by serejke** [IFMO-MobDev-2014/extratask1#52]
Можно ли сдавать экзамен не со своей группой?
Я из 2538, хочу сдавать 21 января

**Comment by thevery** [comment]
Да, с предварительной "регистрацией" (==заранее сообщить об этом и получить аппрув).

**Comment by serejke** [comment]
Патрикеев Сергей 2538, сообщил

**Comment by dimatomp** [comment]
Томп Дмитрий 2539, хочу сдать 23-го (если сдавать позже разрешается).

**Comment by thevery** [comment]
Ok
